language: node_js
node_js:
  - "8"

script:
  - npm run generate

deploy:
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    repo: COSCUP/coscup2018-website-staging
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: staging-2018.coscup.org
    on:
      branch:
        - dev
        - staging
  - provider: pages
    local-dir: dist/
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: 2018.coscup.org
    on:
      branch:
        - master
        - production
